### ISSUE TITLE
Criar - Telas de Autenticação

### ISSUE THREAD

**Issue by julianoscordeiro** [julianoscordeiro/Projeto-ACA#1]
- [x] Criar tela de login e registro
- [x] Criar backend login e registro
- [x] Criar tela de Esqueceu senha

![image](https://user-images.githubusercontent.com/53874458/62652589-1f87af00-b932-11e9-9b4f-67cfab2659bf.png)

**Comment by fernandohous** [comment]
Fiz a parte do design das telas.

**Comment by julianoscordeiro** [comment]
Utilizar o Framwork Laravel
